// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: example/api/helloworld/helloworld.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Greeter_DELETEUriBindingJSONRender_FullMethodName                = "/helloworld.Greeter/DELETEUriBindingJSONRender"
	Greeter_GETUriBindingIndentedJSONRender_FullMethodName           = "/helloworld.Greeter/GETUriBindingIndentedJSONRender"
	Greeter_GETUriQueryBindingSecureJSONRender_FullMethodName        = "/helloworld.Greeter/GETUriQueryBindingSecureJSONRender"
	Greeter_POSTHeaderFormPostBindingJSONPJSONRender_FullMethodName  = "/helloworld.Greeter/POSTHeaderFormPostBindingJSONPJSONRender"
	Greeter_PATCHHeaderProtoFormBindingPureJSONRender_FullMethodName = "/helloworld.Greeter/PATCHHeaderProtoFormBindingPureJSONRender"
	Greeter_PUTHeaderJSONBindingAsciiJSONRender_FullMethodName       = "/helloworld.Greeter/PUTHeaderJSONBindingAsciiJSONRender"
	Greeter_POSTProtoBufBindingProtoBufRender_FullMethodName         = "/helloworld.Greeter/POSTProtoBufBindingProtoBufRender"
	Greeter_POSTProtoJSONBindingProtoJSONRender_FullMethodName       = "/helloworld.Greeter/POSTProtoJSONBindingProtoJSONRender"
	Greeter_POSTCustomBindingCustomRender_FullMethodName             = "/helloworld.Greeter/POSTCustomBindingCustomRender"
	Greeter_NotDefine_FullMethodName                                 = "/helloworld.Greeter/NotDefine"
	Greeter_POSTSetHeaderTrailer_FullMethodName                      = "/helloworld.Greeter/POSTSetHeaderTrailer"
	Greeter_POSTError_FullMethodName                                 = "/helloworld.Greeter/POSTError"
	Greeter_POSTGRPCStatus_FullMethodName                            = "/helloworld.Greeter/POSTGRPCStatus"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// @GORS @DELETE @Path(/UriBinding/JSONRender/:name) @UriBinding @JSONRender
	DELETEUriBindingJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @GET @Path(/UriBinding/IndentedJSONRender/:name) @UriBinding @IndentedJSONRender
	GETUriBindingIndentedJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @GET @Path(/UriQueryBinding/SecureJSONRender/:name) @UriBinding @QueryBinding @SecureJSONRender
	GETUriQueryBindingSecureJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @POST @Path(/HeaderFormPostBinding/JSONPJSONRender) @HeaderBinding @FormPostBinding @JSONPJSONRender
	POSTHeaderFormPostBindingJSONPJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @PATCH @Path(/HeaderProtoFormBinding/PureJSONRender) @HeaderBinding @FormBinding @PureJSONRender
	PATCHHeaderProtoFormBindingPureJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @PUT @Path(/HeaderJSONBinding/AsciiJSONRender) @HeaderBinding @JSONBinding @AsciiJSONRender
	PUTHeaderJSONBindingAsciiJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @POST @Path(/ProtoBufBinding/ProtoBufRender) @ProtoBufBinding @ProtoBufRender
	POSTProtoBufBindingProtoBufRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @POST @Path(/ProtoJSONBinding/ProtoJSONRender) @ProtoJSONBinding @ProtoJSONRender
	POSTProtoJSONBindingProtoJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @POST @Path(/CustomBinding/CustomRender) @CustomBinding @CustomRender
	POSTCustomBindingCustomRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	NotDefine(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @POST @Path(/POSTSetHeaderTrailer) @ProtoJSONBinding @ProtoJSONRender
	POSTSetHeaderTrailer(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @POST @Path(/Error) @ProtoJSONBinding @ProtoJSONRender
	POSTError(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// @GORS @POST @Path(/GRPCStatus) @ProtoJSONBinding @ProtoJSONRender
	POSTGRPCStatus(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) DELETEUriBindingJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_DELETEUriBindingJSONRender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GETUriBindingIndentedJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_GETUriBindingIndentedJSONRender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GETUriQueryBindingSecureJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_GETUriQueryBindingSecureJSONRender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) POSTHeaderFormPostBindingJSONPJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_POSTHeaderFormPostBindingJSONPJSONRender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) PATCHHeaderProtoFormBindingPureJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_PATCHHeaderProtoFormBindingPureJSONRender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) PUTHeaderJSONBindingAsciiJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_PUTHeaderJSONBindingAsciiJSONRender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) POSTProtoBufBindingProtoBufRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_POSTProtoBufBindingProtoBufRender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) POSTProtoJSONBindingProtoJSONRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_POSTProtoJSONBindingProtoJSONRender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) POSTCustomBindingCustomRender(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_POSTCustomBindingCustomRender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) NotDefine(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_NotDefine_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) POSTSetHeaderTrailer(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_POSTSetHeaderTrailer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) POSTError(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_POSTError_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) POSTGRPCStatus(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_POSTGRPCStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// @GORS @DELETE @Path(/UriBinding/JSONRender/:name) @UriBinding @JSONRender
	DELETEUriBindingJSONRender(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @GET @Path(/UriBinding/IndentedJSONRender/:name) @UriBinding @IndentedJSONRender
	GETUriBindingIndentedJSONRender(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @GET @Path(/UriQueryBinding/SecureJSONRender/:name) @UriBinding @QueryBinding @SecureJSONRender
	GETUriQueryBindingSecureJSONRender(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @POST @Path(/HeaderFormPostBinding/JSONPJSONRender) @HeaderBinding @FormPostBinding @JSONPJSONRender
	POSTHeaderFormPostBindingJSONPJSONRender(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @PATCH @Path(/HeaderProtoFormBinding/PureJSONRender) @HeaderBinding @FormBinding @PureJSONRender
	PATCHHeaderProtoFormBindingPureJSONRender(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @PUT @Path(/HeaderJSONBinding/AsciiJSONRender) @HeaderBinding @JSONBinding @AsciiJSONRender
	PUTHeaderJSONBindingAsciiJSONRender(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @POST @Path(/ProtoBufBinding/ProtoBufRender) @ProtoBufBinding @ProtoBufRender
	POSTProtoBufBindingProtoBufRender(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @POST @Path(/ProtoJSONBinding/ProtoJSONRender) @ProtoJSONBinding @ProtoJSONRender
	POSTProtoJSONBindingProtoJSONRender(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @POST @Path(/CustomBinding/CustomRender) @CustomBinding @CustomRender
	POSTCustomBindingCustomRender(context.Context, *HelloRequest) (*HelloReply, error)
	NotDefine(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @POST @Path(/POSTSetHeaderTrailer) @ProtoJSONBinding @ProtoJSONRender
	POSTSetHeaderTrailer(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @POST @Path(/Error) @ProtoJSONBinding @ProtoJSONRender
	POSTError(context.Context, *HelloRequest) (*HelloReply, error)
	// @GORS @POST @Path(/GRPCStatus) @ProtoJSONBinding @ProtoJSONRender
	POSTGRPCStatus(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) DELETEUriBindingJSONRender(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DELETEUriBindingJSONRender not implemented")
}
func (UnimplementedGreeterServer) GETUriBindingIndentedJSONRender(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GETUriBindingIndentedJSONRender not implemented")
}
func (UnimplementedGreeterServer) GETUriQueryBindingSecureJSONRender(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GETUriQueryBindingSecureJSONRender not implemented")
}
func (UnimplementedGreeterServer) POSTHeaderFormPostBindingJSONPJSONRender(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method POSTHeaderFormPostBindingJSONPJSONRender not implemented")
}
func (UnimplementedGreeterServer) PATCHHeaderProtoFormBindingPureJSONRender(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PATCHHeaderProtoFormBindingPureJSONRender not implemented")
}
func (UnimplementedGreeterServer) PUTHeaderJSONBindingAsciiJSONRender(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PUTHeaderJSONBindingAsciiJSONRender not implemented")
}
func (UnimplementedGreeterServer) POSTProtoBufBindingProtoBufRender(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method POSTProtoBufBindingProtoBufRender not implemented")
}
func (UnimplementedGreeterServer) POSTProtoJSONBindingProtoJSONRender(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method POSTProtoJSONBindingProtoJSONRender not implemented")
}
func (UnimplementedGreeterServer) POSTCustomBindingCustomRender(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method POSTCustomBindingCustomRender not implemented")
}
func (UnimplementedGreeterServer) NotDefine(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotDefine not implemented")
}
func (UnimplementedGreeterServer) POSTSetHeaderTrailer(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method POSTSetHeaderTrailer not implemented")
}
func (UnimplementedGreeterServer) POSTError(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method POSTError not implemented")
}
func (UnimplementedGreeterServer) POSTGRPCStatus(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method POSTGRPCStatus not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_DELETEUriBindingJSONRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).DELETEUriBindingJSONRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_DELETEUriBindingJSONRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).DELETEUriBindingJSONRender(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GETUriBindingIndentedJSONRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GETUriBindingIndentedJSONRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GETUriBindingIndentedJSONRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GETUriBindingIndentedJSONRender(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GETUriQueryBindingSecureJSONRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GETUriQueryBindingSecureJSONRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GETUriQueryBindingSecureJSONRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GETUriQueryBindingSecureJSONRender(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_POSTHeaderFormPostBindingJSONPJSONRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).POSTHeaderFormPostBindingJSONPJSONRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_POSTHeaderFormPostBindingJSONPJSONRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).POSTHeaderFormPostBindingJSONPJSONRender(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_PATCHHeaderProtoFormBindingPureJSONRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).PATCHHeaderProtoFormBindingPureJSONRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_PATCHHeaderProtoFormBindingPureJSONRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).PATCHHeaderProtoFormBindingPureJSONRender(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_PUTHeaderJSONBindingAsciiJSONRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).PUTHeaderJSONBindingAsciiJSONRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_PUTHeaderJSONBindingAsciiJSONRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).PUTHeaderJSONBindingAsciiJSONRender(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_POSTProtoBufBindingProtoBufRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).POSTProtoBufBindingProtoBufRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_POSTProtoBufBindingProtoBufRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).POSTProtoBufBindingProtoBufRender(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_POSTProtoJSONBindingProtoJSONRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).POSTProtoJSONBindingProtoJSONRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_POSTProtoJSONBindingProtoJSONRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).POSTProtoJSONBindingProtoJSONRender(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_POSTCustomBindingCustomRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).POSTCustomBindingCustomRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_POSTCustomBindingCustomRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).POSTCustomBindingCustomRender(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_NotDefine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).NotDefine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_NotDefine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).NotDefine(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_POSTSetHeaderTrailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).POSTSetHeaderTrailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_POSTSetHeaderTrailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).POSTSetHeaderTrailer(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_POSTError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).POSTError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_POSTError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).POSTError(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_POSTGRPCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).POSTGRPCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_POSTGRPCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).POSTGRPCStatus(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DELETEUriBindingJSONRender",
			Handler:    _Greeter_DELETEUriBindingJSONRender_Handler,
		},
		{
			MethodName: "GETUriBindingIndentedJSONRender",
			Handler:    _Greeter_GETUriBindingIndentedJSONRender_Handler,
		},
		{
			MethodName: "GETUriQueryBindingSecureJSONRender",
			Handler:    _Greeter_GETUriQueryBindingSecureJSONRender_Handler,
		},
		{
			MethodName: "POSTHeaderFormPostBindingJSONPJSONRender",
			Handler:    _Greeter_POSTHeaderFormPostBindingJSONPJSONRender_Handler,
		},
		{
			MethodName: "PATCHHeaderProtoFormBindingPureJSONRender",
			Handler:    _Greeter_PATCHHeaderProtoFormBindingPureJSONRender_Handler,
		},
		{
			MethodName: "PUTHeaderJSONBindingAsciiJSONRender",
			Handler:    _Greeter_PUTHeaderJSONBindingAsciiJSONRender_Handler,
		},
		{
			MethodName: "POSTProtoBufBindingProtoBufRender",
			Handler:    _Greeter_POSTProtoBufBindingProtoBufRender_Handler,
		},
		{
			MethodName: "POSTProtoJSONBindingProtoJSONRender",
			Handler:    _Greeter_POSTProtoJSONBindingProtoJSONRender_Handler,
		},
		{
			MethodName: "POSTCustomBindingCustomRender",
			Handler:    _Greeter_POSTCustomBindingCustomRender_Handler,
		},
		{
			MethodName: "NotDefine",
			Handler:    _Greeter_NotDefine_Handler,
		},
		{
			MethodName: "POSTSetHeaderTrailer",
			Handler:    _Greeter_POSTSetHeaderTrailer_Handler,
		},
		{
			MethodName: "POSTError",
			Handler:    _Greeter_POSTError_Handler,
		},
		{
			MethodName: "POSTGRPCStatus",
			Handler:    _Greeter_POSTGRPCStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/helloworld/helloworld.proto",
}
