// Code generated by "gors -service BindingRender"; DO NOT EDIT.
package demo

import (
	context "context"
	gin "github.com/gin-gonic/gin"
	binding "github.com/gin-gonic/gin/binding"
	render "github.com/gin-gonic/gin/render"
	gors "github.com/go-leo/gors"
	pb "github.com/go-leo/gors/example/api/pb"
	http "net/http"
)

func BindingRenderRouters(srv BindingRender) []gors.Router {
	return []gors.Router{
		{
			HTTPMethod: http.MethodGet,
			Path:       "/api/BindingRender/UriBindingIndentedJSONRender/:id",
			HandlerFunc: func(c *gin.Context) {
				req := new(UriBindingReq)
				if err := c.BindUri(req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.UriBindingIndentedJSONRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.IndentedJSON(statusCode, resp)
			},
		},
		{
			HTTPMethod: http.MethodGet,
			Path:       "/api/BindingRender/QueryBindingSecureJSONRender/:id",
			HandlerFunc: func(c *gin.Context) {
				req := new(QueryBindingReq)
				if err := c.BindUri(req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Query); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.QueryBindingSecureJSONRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.SecureJSON(statusCode, resp)
			},
		},
		{
			HTTPMethod: http.MethodGet,
			Path:       "/api/BindingRender/HeaderBindingJsonpJSONRender/:id",
			HandlerFunc: func(c *gin.Context) {
				req := new(HeaderBindingReq)
				if err := c.BindUri(req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Query); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Header); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.HeaderBindingJsonpJSONRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.JSONP(statusCode, resp)
			},
		},
		{
			HTTPMethod: http.MethodPost,
			Path:       "/api/BindingRender/JSONBindingJSONRender/:id",
			HandlerFunc: func(c *gin.Context) {
				req := new(JSONBindingReq)
				if err := c.BindUri(req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Query); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Header); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.JSON); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.JSONBindingJSONRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.JSON(statusCode, resp)
			},
		},
		{
			HTTPMethod: http.MethodPatch,
			Path:       "/api/BindingRender/XMLBindingXMLRender/:id",
			HandlerFunc: func(c *gin.Context) {
				req := new(XMLBindingReq)
				if err := c.BindUri(req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Query); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Header); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.XML); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.XMLBindingXMLRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.XML(statusCode, resp)
			},
		},
		{
			HTTPMethod: http.MethodPost,
			Path:       "/api/BindingRender/FormBindingJSONRender/:id",
			HandlerFunc: func(c *gin.Context) {
				req := new(FormBindingReq)
				if err := c.BindUri(req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Query); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Header); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Form); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.FormBindingJSONRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.JSON(statusCode, resp)
			},
		},
		{
			HTTPMethod: http.MethodPost,
			Path:       "/api/BindingRender/FormPostBindingPureJSONRender/:id",
			HandlerFunc: func(c *gin.Context) {
				req := new(FormPostBindingReq)
				if err := c.BindUri(req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Query); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Header); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.FormPost); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.FormPostBindingPureJSONRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.PureJSON(statusCode, resp)
			},
		},
		{
			HTTPMethod: http.MethodPost,
			Path:       "/api/BindingRender/FormMultipartBindingAsciiJSONRender/:id",
			HandlerFunc: func(c *gin.Context) {
				req := new(FormMultipartBindingReq)
				if err := c.BindUri(req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Query); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.Header); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err := c.ShouldBindWith(req, binding.FormMultipart); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.FormMultipartBindingAsciiJSONRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.AsciiJSON(statusCode, resp)
			},
		},
		{
			HTTPMethod: http.MethodPut,
			Path:       "/api/BindingRender/ProtoBufBindingProtoBufRender",
			HandlerFunc: func(c *gin.Context) {
				req := new(pb.ProtoBufReq)
				if err := c.ShouldBindWith(req, binding.ProtoBuf); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.ProtoBufBindingProtoBufRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.ProtoBuf(statusCode, resp)
			},
		},
		{
			HTTPMethod: http.MethodDelete,
			Path:       "/api/BindingRender/MsgPackBindingMsgPackRender",
			HandlerFunc: func(c *gin.Context) {
				req := new(MsgPackBindingReq)
				if err := c.ShouldBindWith(req, binding.MsgPack); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.MsgPackBindingMsgPackRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.Render(statusCode, render.MsgPack{Data: resp})
			},
		},
		{
			HTTPMethod: http.MethodConnect,
			Path:       "/api/BindingRender/YAMLBindingYAMLRender",
			HandlerFunc: func(c *gin.Context) {
				req := new(YAMLBindingReq)
				if err := c.ShouldBindWith(req, binding.YAML); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.YAMLBindingYAMLRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.YAML(statusCode, resp)
			},
		},
		{
			HTTPMethod: http.MethodOptions,
			Path:       "/api/BindingRender/TOMLBindingTOMLRender",
			HandlerFunc: func(c *gin.Context) {
				req := new(TOMLBindingReq)
				if err := c.ShouldBindWith(req, binding.TOML); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				var ctx context.Context = c
				ctx = gors.InjectStatusCode(ctx, http.StatusOK)
				ctx = gors.InjectHeader(ctx, c.Writer.Header())
				resp, err := srv.TOMLBindingTOMLRender(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.ExtractStatusCode(ctx)
				c.TOML(statusCode, resp)
			},
		},
	}
}
