// Code generated by "gors -service BytesString"; DO NOT EDIT.

package demo

import (
	gin "github.com/gin-gonic/gin"
	gors "github.com/go-leo/gors"
	io "io"
	http "net/http"
)

func BytesStringRoutes(srv BytesString) []gors.Route {
	return []gors.Route{
		gors.NewRoute(
			http.MethodGet,
			"/api/BytesString/Get",
			func(c *gin.Context) {
				var req []byte
				var resp string
				var err error
				var body []byte
				body, err = io.ReadAll(c.Request.Body)
				if err != nil {
					gors.HandleBadRequest(c, err)
					return
				}
				req = body
				ctx := gors.NewContext(c)
				resp, err = srv.GetBytesString(ctx, req)
				if err != nil {
					gors.HTTPErrorRender(c, err)
					return
				}
				gors.HTMLRender(c, gors.HTTPStatusCode(ctx), resp, "text/html; charset=utf-8")
			},
		),
		gors.NewRoute(
			http.MethodPut,
			"/api/BytesString/Put",
			func(c *gin.Context) {
				var req []byte
				var resp string
				var err error
				var body []byte
				body, err = io.ReadAll(c.Request.Body)
				if err != nil {
					gors.HandleBadRequest(c, err)
					return
				}
				req = body
				ctx := gors.NewContext(c)
				resp, err = srv.PutBytesString(ctx, req)
				if err != nil {
					gors.HTTPErrorRender(c, err)
					return
				}
				gors.RedirectRender(c, gors.HTTPStatusCode(ctx), resp, "")
			},
		),
	}
}
