// Code generated by "gors -service BytesReader"; DO NOT EDIT.

package demo

import (
	gin "github.com/gin-gonic/gin"
	gors "github.com/go-leo/gors"
	io "io"
	http "net/http"
)

func BytesReaderRoutes(srv BytesReader) []gors.Route {
	return []gors.Route{
		gors.NewRoute(
			http.MethodGet,
			"/api/BytesReader/Get",
			func(c *gin.Context) {
				var req []byte
				var resp io.Reader
				var err error
				var body []byte
				body, err = io.ReadAll(c.Request.Body)
				if err != nil {
					gors.HandleBadRequest(c, err)
					return
				}
				req = body
				ctx := gors.NewContext(c)
				resp, err = srv.GetBytesReader(ctx, req)
				if err != nil {
					gors.HTTPErrorRender(c, err)
					return
				}
				gors.ReaderRender(c, gors.HTTPStatusCode(ctx), resp, "video/mpeg4")
			},
		),
		gors.NewRoute(
			http.MethodPatch,
			"/api/BytesReader/Patch",
			func(c *gin.Context) {
				var req []byte
				var resp io.Reader
				var err error
				var body []byte
				body, err = io.ReadAll(c.Request.Body)
				if err != nil {
					gors.HandleBadRequest(c, err)
					return
				}
				req = body
				ctx := gors.NewContext(c)
				resp, err = srv.PatchBytesReader(ctx, req)
				if err != nil {
					gors.HTTPErrorRender(c, err)
					return
				}
				gors.ReaderRender(c, gors.HTTPStatusCode(ctx), resp, "video/mpeg4")
			},
		),
	}
}
