// Code generated by "gors -service CustomBinderRender"; DO NOT EDIT.

package demo

import (
	gin "github.com/gin-gonic/gin"
	gors "github.com/go-leo/gors"
	http "net/http"
)

func CustomBinderRenderRoutes(srv CustomBinderRender) []gors.Route {
	return []gors.Route{
		gors.NewRoute(
			http.MethodPost,
			"/api/CustomBinderRender/Custom",
			func(c *gin.Context) {
				var req *CustomReq
				var resp *CustomResp
				var err error
				req = new(CustomReq)
				if err := gors.ShouldBind(
					c, req,
					gors.CustomBinding,
				); err != nil {
					gors.HandleBadRequest(c, err)
					return
				}
				if err = gors.Validate(req); err != nil {
					gors.HandleBadRequest(c, err)
					return
				}
				ctx := gors.NewContext(c)
				resp, err = srv.Custom(ctx, req)
				gors.MustRender(c, resp, err, "", gors.CustomRender)
			},
		),
	}
}
