// Code generated by "gors -service ReaderBytes"; DO NOT EDIT.

package demo

import (
	gin "github.com/gin-gonic/gin"
	gors "github.com/go-leo/gors"
	io "io"
	http "net/http"
)

func ReaderBytesRoutes(srv ReaderBytes, opts ...gors.Option) []gors.Route {
	options := gors.New(opts...)
	_ = options
	return []gors.Route{
		gors.NewRoute(
			http.MethodGet,
			"/api/ReaderBytes/Get",
			func(c *gin.Context) {
				var ctx = gors.NewContext(c)
				var req io.Reader
				var resp []byte
				var err error
				req = c.Request.Body
				resp, err = srv.GetReaderBytes(ctx, req)
				if err != nil {
					gors.ErrorRender(ctx, err, options.ErrorHandler)
					return
				}
				gors.ResponseRender(ctx, gors.StatusCode(ctx), resp, "", gors.BytesRender, options.ResponseWrapper)
			},
		),
		gors.NewRoute(
			http.MethodPost,
			"/api/ReaderBytes/Post",
			func(c *gin.Context) {
				var ctx = gors.NewContext(c)
				var req io.Reader
				var resp []byte
				var err error
				req = c.Request.Body
				resp, err = srv.PostReaderBytes(ctx, req)
				if err != nil {
					gors.ErrorRender(ctx, err, options.ErrorHandler)
					return
				}
				gors.ResponseRender(ctx, gors.StatusCode(ctx), resp, "text/go", gors.BytesRender, options.ResponseWrapper)
			},
		),
	}
}
