// Code generated by "gors -service ReaderBytes"; DO NOT EDIT.
package demo

import (
	gin "github.com/gin-gonic/gin"
	render "github.com/gin-gonic/gin/render"
	gors "github.com/go-leo/gors"
	io "io"
	http "net/http"
)

func ReaderBytesRoutes(srv ReaderBytes) []gors.Route {
	return []gors.Route{
		{
			HTTPMethod: http.MethodGet,
			Path:       "/api/ReaderBytes/Get",
			HandlerFunc: func(c *gin.Context) {
				var req io.Reader
				var resp []byte
				var err error
				req = c.Request.Body
				ctx := gors.NewContext(c)
				resp, err = srv.GetReaderBytes(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.GetCodeFromContext(ctx)
				c.Render(statusCode, render.Data{ContentType: "", Data: resp})
			},
		},
		{
			HTTPMethod: http.MethodPost,
			Path:       "/api/ReaderBytes/Post",
			HandlerFunc: func(c *gin.Context) {
				var req io.Reader
				var resp []byte
				var err error
				req = c.Request.Body
				ctx := gors.NewContext(c)
				resp, err = srv.PostReaderBytes(ctx, req)
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.GetCodeFromContext(ctx)
				c.Render(statusCode, render.Data{ContentType: "text/go", Data: resp})
			},
		},
	}
}
