// Code generated by "gors -service Service"; DO NOT EDIT.

package demo

import (
	gin "github.com/gin-gonic/gin"
	gors "github.com/go-leo/gors"
	http "net/http"
)

func ServiceRoutes(srv Service, opts ...gors.Option) []gors.Route {
	options := gors.New(opts...)
	_ = options
	return []gors.Route{
		gors.NewRoute(
			http.MethodGet,
			"/api/v1/method/:id",
			func(c *gin.Context) {
				var ctx = gors.NewContext(c)
				var req *MethodReq
				var resp *MethodResp
				var err error
				req = new(MethodReq)
				if err = gors.RequestBind(
					ctx, req, options.Tag,
					gors.UriBinding,
				); err != nil {
					gors.ErrorRender(ctx, err, options.ErrorHandler)
					return
				}
				resp, err = srv.Method(ctx, req)
				if err != nil {
					gors.ErrorRender(ctx, err, options.ErrorHandler)
					return
				}
				gors.ResponseRender(ctx, gors.StatusCode(ctx), resp, "", gors.JSONRender, options.ResponseWrapper)
			},
		),
	}
}
