// Code generated by "gors -service StringString"; DO NOT EDIT.

package demo

import (
	gin "github.com/gin-gonic/gin"
	gors "github.com/go-leo/gors"
	convx "github.com/go-leo/gox/convx"
	io "io"
	http "net/http"
)

func StringStringRoutes(srv StringString) []gors.Route {
	return []gors.Route{
		gors.NewRoute(
			http.MethodGet,
			"/api/StringString/Get",
			func(c *gin.Context) {
				var req string
				var resp string
				var err error
				var body []byte
				body, err = io.ReadAll(c.Request.Body)
				if err != nil {
					gors.HandleBadRequest(c, err)
					return
				}
				req = convx.BytesToString(body)
				ctx := gors.NewContext(c)
				resp, err = srv.GetStringString(ctx, req)
				gors.MustRender(c, resp, err, "text/go", gors.StringRender)
			},
		),
		gors.NewRoute(
			http.MethodPatch,
			"/api/StringString/Patch",
			func(c *gin.Context) {
				var req string
				var resp string
				var err error
				var body []byte
				body, err = io.ReadAll(c.Request.Body)
				if err != nil {
					gors.HandleBadRequest(c, err)
					return
				}
				req = convx.BytesToString(body)
				ctx := gors.NewContext(c)
				resp, err = srv.PatchStringString(ctx, req)
				gors.MustRender(c, resp, err, "text/go", gors.StringRender)
			},
		),
	}
}
