// Code generated by "gors -service StringReader"; DO NOT EDIT.

package demo

import (
	gin "github.com/gin-gonic/gin"
	gors "github.com/go-leo/gors"
	convx "github.com/go-leo/gox/convx"
	io "io"
	http "net/http"
)

func StringReaderRoutes(srv StringReader) []gors.Route {
	return []gors.Route{
		gors.NewRoute(
			http.MethodGet,
			"/api/StringReader/Get",
			func(c *gin.Context) {
				var req string
				var resp io.Reader
				var err error
				var body []byte
				body, err = io.ReadAll(c.Request.Body)
				if err != nil {
					gors.HandleBadRequest(c, err)
					return
				}
				req = convx.BytesToString(body)
				ctx := gors.NewContext(c)
				resp, err = srv.GetStringRender(ctx, req)
				if err != nil {
					gors.HTTPErrorRender(c, err)
					return
				}
				gors.ReaderRender(c, gors.HTTPStatusCode(ctx), resp, "video/mpeg4")
			},
		),
		gors.NewRoute(
			http.MethodOptions,
			"/api/StringReader/Options",
			func(c *gin.Context) {
				var req string
				var resp io.Reader
				var err error
				var body []byte
				body, err = io.ReadAll(c.Request.Body)
				if err != nil {
					gors.HandleBadRequest(c, err)
					return
				}
				req = convx.BytesToString(body)
				ctx := gors.NewContext(c)
				resp, err = srv.OptionsStringReader(ctx, req)
				if err != nil {
					gors.HTTPErrorRender(c, err)
					return
				}
				gors.ReaderRender(c, gors.HTTPStatusCode(ctx), resp, "video/mpeg4")
			},
		),
	}
}
