// Code generated by protoc-gen-gors. DO NOT EDIT.

package endpointsapis

import (
	context "context"
	fmt "fmt"
	v2 "github.com/go-leo/gors/v2"
	urlx "github.com/go-leo/gox/netx/urlx"
	mux "github.com/gorilla/mux"
	protojson "google.golang.org/protobuf/encoding/protojson"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
)

type WorkspacesGorsService interface {
	ListWorkspaces(ctx context.Context, request *ListWorkspacesRequest) (*ListWorkspacesResponse, error)
	GetWorkspace(ctx context.Context, request *GetWorkspaceRequest) (*Workspace, error)
	CreateWorkspace(ctx context.Context, request *CreateWorkspaceRequest) (*Workspace, error)
	UpdateWorkspace(ctx context.Context, request *UpdateWorkspaceRequest) (*Workspace, error)
	DeleteWorkspace(ctx context.Context, request *DeleteWorkspaceRequest) (*emptypb.Empty, error)
}

func AppendWorkspacesGorsRoute(router *mux.Router, service WorkspacesGorsService, opts ...v2.Option) *mux.Router {
	options := v2.NewOptions(opts...)
	handler := workspacesGorsHandler{
		service: service,
		decoder: workspacesGorsRequestDecoder{
			unmarshalOptions: options.UnmarshalOptions(),
		},
		encoder: workspacesGorsResponseEncoder{
			marshalOptions:      options.MarshalOptions(),
			unmarshalOptions:    options.UnmarshalOptions(),
			responseTransformer: options.ResponseTransformer(),
		},
		errorEncoder: v2.DefaultErrorEncoder,
	}
	router.NewRoute().
		Name("/google.example.endpointsapis.v1.Workspaces/ListWorkspaces").
		Methods("GET").
		Path("/v1/projects/{project}/locations/{location}/workspaces").
		Handler(handler.ListWorkspaces())
	router.NewRoute().
		Name("/google.example.endpointsapis.v1.Workspaces/GetWorkspace").
		Methods("GET").
		Path("/v1/projects/{project}/locations/{location}/workspaces/{workspac}").
		Handler(handler.GetWorkspace())
	router.NewRoute().
		Name("/google.example.endpointsapis.v1.Workspaces/CreateWorkspace").
		Methods("POST").
		Path("/v1/projects/{project}/locations/{location}/workspaces").
		Handler(handler.CreateWorkspace())
	router.NewRoute().
		Name("/google.example.endpointsapis.v1.Workspaces/UpdateWorkspace").
		Methods("PATCH").
		Path("/v1/projects/{project}/locations/{location}/Workspaces/{Workspac}").
		Handler(handler.UpdateWorkspace())
	router.NewRoute().
		Name("/google.example.endpointsapis.v1.Workspaces/DeleteWorkspace").
		Methods("DELETE").
		Path("/v1/projects/{project}/locations/{location}/workspaces/{workspac}").
		Handler(handler.DeleteWorkspace())
	return router
}

type workspacesGorsHandler struct {
	service      WorkspacesGorsService
	decoder      workspacesGorsRequestDecoder
	encoder      workspacesGorsResponseEncoder
	errorEncoder v2.ErrorEncoder
}

func (h workspacesGorsHandler) ListWorkspaces() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.ListWorkspaces(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.ListWorkspaces(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.ListWorkspaces(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h workspacesGorsHandler) GetWorkspace() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.GetWorkspace(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.GetWorkspace(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.GetWorkspace(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h workspacesGorsHandler) CreateWorkspace() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.CreateWorkspace(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.CreateWorkspace(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.CreateWorkspace(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h workspacesGorsHandler) UpdateWorkspace() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.UpdateWorkspace(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.UpdateWorkspace(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.UpdateWorkspace(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h workspacesGorsHandler) DeleteWorkspace() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.DeleteWorkspace(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.DeleteWorkspace(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.DeleteWorkspace(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

type workspacesGorsRequestDecoder struct {
	unmarshalOptions protojson.UnmarshalOptions
}

func (decoder workspacesGorsRequestDecoder) ListWorkspaces(ctx context.Context, r *http.Request) (*ListWorkspacesRequest, error) {
	req := &ListWorkspacesRequest{}
	vars := urlx.FormFromMap(mux.Vars(r))
	req.Parent = fmt.Sprintf("projects/%s/locations/%s", vars.Get("project"), vars.Get("location"))
	queries := r.URL.Query()
	var queryErr error
	req.PageSize, queryErr = v2.FormDecoder[int32](queryErr, queries, "page_size", urlx.GetInt)
	req.PageToken = queries.Get("page_token")
	if queryErr != nil {
		return nil, queryErr
	}
	return req, nil
}
func (decoder workspacesGorsRequestDecoder) GetWorkspace(ctx context.Context, r *http.Request) (*GetWorkspaceRequest, error) {
	req := &GetWorkspaceRequest{}
	vars := urlx.FormFromMap(mux.Vars(r))
	req.Name = fmt.Sprintf("projects/%s/locations/%s/workspaces/%s", vars.Get("project"), vars.Get("location"), vars.Get("workspac"))
	return req, nil
}
func (decoder workspacesGorsRequestDecoder) CreateWorkspace(ctx context.Context, r *http.Request) (*CreateWorkspaceRequest, error) {
	req := &CreateWorkspaceRequest{}
	if req.Workspace == nil {
		req.Workspace = &Workspace{}
	}
	if err := v2.RequestDecoder(ctx, r, req.Workspace, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	vars := urlx.FormFromMap(mux.Vars(r))
	req.Parent = fmt.Sprintf("projects/%s/locations/%s", vars.Get("project"), vars.Get("location"))
	return req, nil
}
func (decoder workspacesGorsRequestDecoder) UpdateWorkspace(ctx context.Context, r *http.Request) (*UpdateWorkspaceRequest, error) {
	req := &UpdateWorkspaceRequest{}
	if req.Workspace == nil {
		req.Workspace = &Workspace{}
	}
	if err := v2.RequestDecoder(ctx, r, req.Workspace, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	vars := urlx.FormFromMap(mux.Vars(r))
	req.Name = fmt.Sprintf("projects/%s/locations/%s/Workspaces/%s", vars.Get("project"), vars.Get("location"), vars.Get("Workspac"))
	return req, nil
}
func (decoder workspacesGorsRequestDecoder) DeleteWorkspace(ctx context.Context, r *http.Request) (*DeleteWorkspaceRequest, error) {
	req := &DeleteWorkspaceRequest{}
	vars := urlx.FormFromMap(mux.Vars(r))
	req.Name = fmt.Sprintf("projects/%s/locations/%s/workspaces/%s", vars.Get("project"), vars.Get("location"), vars.Get("workspac"))
	return req, nil
}

type workspacesGorsResponseEncoder struct {
	marshalOptions      protojson.MarshalOptions
	unmarshalOptions    protojson.UnmarshalOptions
	responseTransformer v2.ResponseTransformer
}

func (encoder workspacesGorsResponseEncoder) ListWorkspaces(ctx context.Context, w http.ResponseWriter, resp *ListWorkspacesResponse) error {
	return v2.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder workspacesGorsResponseEncoder) GetWorkspace(ctx context.Context, w http.ResponseWriter, resp *Workspace) error {
	return v2.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder workspacesGorsResponseEncoder) CreateWorkspace(ctx context.Context, w http.ResponseWriter, resp *Workspace) error {
	return v2.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder workspacesGorsResponseEncoder) UpdateWorkspace(ctx context.Context, w http.ResponseWriter, resp *Workspace) error {
	return v2.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder workspacesGorsResponseEncoder) DeleteWorkspace(ctx context.Context, w http.ResponseWriter, resp *emptypb.Empty) error {
	return v2.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
