// Code generated by protoc-gen-go-gors. DO NOT EDIT.

package protoservice

import (
	gin "github.com/gin-gonic/gin"
	gors "github.com/go-leo/gors"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	http "net/http"
)

func ProtoServiceClientRoutes(cli ProtoServiceClient, opts ...gors.Option) []gors.Route {
	options := gors.New(opts...)
	_ = options
	if len(options.Tag) == 0 {
		options.Tag = "json"
	}
	return []gors.Route{
		gors.NewRoute(
			http.MethodPost,
			"/v1/Method",
			func(c *gin.Context) {
				var rpcMethodName = "/protoservice.ProtoService/Method"
				var ctx = gors.NewContext(c, rpcMethodName)
				var req *HelloRequest
				var resp *HelloReply
				var err error
				req = new(HelloRequest)
				if err = gors.RequestBind(
					ctx, req, options.Tag,
					gors.ProtoJSONBinding,
				); err != nil {
					gors.ErrorRender(ctx, err, options.ErrorHandler, options.ResponseWrapper)
					return
				}
				if ctx, err = gors.NewGRPCContext(ctx, options.IncomingHeaderMatcher, options.MetadataAnnotators); err != nil {
					gors.ErrorRender(ctx, err, options.ErrorHandler, options.ResponseWrapper)
					return
				}
				var headerMD, trailerMD metadata.MD
				resp, err = cli.Method(ctx, req, grpc.Header(&headerMD), grpc.Trailer(&trailerMD))
				gors.AddGRPCMetadata(ctx, headerMD, trailerMD, options.OutgoingHeaderMatcher)
				if err != nil {
					gors.ErrorRender(ctx, err, options.ErrorHandler, options.ResponseWrapper)
					return
				}
				gors.ResponseRender(ctx, gors.StatusCode(ctx), resp, "", gors.ProtoJSONRender, options.ResponseWrapper)
			},
		),
	}
}

func ProtoServiceServerRoutes(srv ProtoServiceServer, opts ...gors.Option) []gors.Route {
	options := gors.New(opts...)
	_ = options
	if len(options.Tag) == 0 {
		options.Tag = "json"
	}
	return []gors.Route{
		gors.NewRoute(
			http.MethodPost,
			"/v1/Method",
			func(c *gin.Context) {
				var rpcMethodName = "/protoservice.ProtoService/Method"
				var ctx = gors.NewContext(c, rpcMethodName)
				var req *HelloRequest
				var resp *HelloReply
				var err error
				req = new(HelloRequest)
				if err = gors.RequestBind(
					ctx, req, options.Tag,
					gors.ProtoJSONBinding,
				); err != nil {
					gors.ErrorRender(ctx, err, options.ErrorHandler, options.ResponseWrapper)
					return
				}
				if ctx, err = gors.NewGRPCContext(ctx, options.IncomingHeaderMatcher, options.MetadataAnnotators); err != nil {
					gors.ErrorRender(ctx, err, options.ErrorHandler, options.ResponseWrapper)
					return
				}
				stream := gors.NewServerTransportStream(rpcMethodName)
				ctx = grpc.NewContextWithServerTransportStream(ctx, stream)
				resp, err = srv.Method(ctx, req)
				gors.AddGRPCMetadata(ctx, stream.Header(), stream.Trailer(), options.OutgoingHeaderMatcher)
				if err != nil {
					gors.ErrorRender(ctx, err, options.ErrorHandler, options.ResponseWrapper)
					return
				}
				gors.ResponseRender(ctx, gors.StatusCode(ctx), resp, "", gors.ProtoJSONRender, options.ResponseWrapper)
			},
		),
	}
}
