package generator

import (
	"github.com/go-leo/gors/v2/internal/gen"
	"google.golang.org/protobuf/compiler/protogen"
	"strconv"
)

type Generator struct {
	Plugin   *protogen.Plugin
	File     *protogen.File
	Services []*gen.Service
}

func NewGenerator(plugin *protogen.Plugin, file *protogen.File) (*Generator, error) {
	services, err := gen.NewServices(file)
	if err != nil {
		return nil, err
	}
	return &Generator{Plugin: plugin, File: file, Services: services}, nil
}

func (f *Generator) Generate() error {
	return f.GenerateFile()
}

func (f *Generator) GenerateFile() error {
	file := f.File
	filename := file.GeneratedFilenamePrefix + "_gors.pb.go"
	g := f.Plugin.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-gors. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	services, err := gen.NewServices(file)
	if err != nil {
		return err
	}

	for _, service := range services {
		if err := f.GenerateServices(service, g); err != nil {
			return err
		}
		if err := f.GenerateAppendServerFunc(service, g); err != nil {
			return err
		}
		if err := f.GenerateHandlers(service, g); err != nil {
			return err
		}
		if err := f.GenerateServerRequestDecoder(service, g); err != nil {
			return err
		}
		if err := f.GenerateServerResponseEncoder(service, g); err != nil {
			return err
		}
	}
	return nil
}

func (f *Generator) GenerateServices(service *gen.Service, g *protogen.GeneratedFile) error {
	g.P("type ", service.ServiceName(), " interface {")
	for _, endpoint := range service.Endpoints {
		g.P(endpoint.Name(), "(ctx ", gen.ContextIdent, ", request *", endpoint.InputGoIdent(), ") (*", endpoint.OutputGoIdent(), ", error)")
	}
	g.P("}")
	g.P()
	return nil
}

func (f *Generator) GenerateAppendServerFunc(service *gen.Service, g *protogen.GeneratedFile) error {
	g.P("func ", service.AppendRouteName(), "(router *", gen.RouterIdent, ", service ", service.ServiceName(), ", opts ...", gen.OptionIdent, ") ", "*", gen.RouterIdent, " {")
	g.P("options := ", gen.NewOptionsIdent, "(opts...)")
	g.P("handler :=  ", service.Unexported(service.HandlerName()), "{")
	g.P("service: service,")
	g.P("decoder: ", service.Unexported(service.RequestDecoderName()), "{")
	g.P("unmarshalOptions: options.UnmarshalOptions(),")
	g.P("},")
	g.P("encoder: ", service.Unexported(service.ResponseEncoderName()), "{")
	g.P("marshalOptions: options.MarshalOptions(),")
	g.P("unmarshalOptions: options.UnmarshalOptions(),")
	g.P("responseTransformer: options.ResponseTransformer(),")
	g.P("},")
	g.P("errorEncoder: ", gen.DefaultErrorEncoderIdent, ",")
	g.P("}")
	for _, endpoint := range service.Endpoints {
		httpRule := endpoint.HttpRule()
		// 调整路径，来适应 github.com/gorilla/mux 路由规则
		path, _, _, _ := httpRule.RegularizePath(httpRule.Path())
		g.P("router.NewRoute().")
		g.P("Name(", strconv.Quote(endpoint.FullName()), ").")
		g.P("Methods(", strconv.Quote(httpRule.Method()), ").")
		g.P("Path(", strconv.Quote(path), ").")
		g.P("Handler(handler.", endpoint.Name(), "())")
	}
	g.P("return router")
	g.P("}")
	g.P()
	return nil
}

func (f *Generator) GenerateHandlers(service *gen.Service, g *protogen.GeneratedFile) error {
	g.P("type ", service.Unexported(service.HandlerName()), " struct {")
	g.P("service ", service.ServiceName())
	g.P("decoder ", service.Unexported(service.RequestDecoderName()))
	g.P("encoder ", service.Unexported(service.ResponseEncoderName()))
	g.P("errorEncoder ", gen.ErrorEncoderIdent)
	g.P("}")
	g.P()
	for _, endpoint := range service.Endpoints {
		g.P("func (h ", service.Unexported(service.HandlerName()), ")", endpoint.Name(), "()", gen.HttpHandlerIdent, " {")
		g.P("return ", gen.HttpHandlerFuncIdent, "(func(writer ", gen.ResponseWriterIdent, ", request *", gen.RequestIdent, ") {")
		g.P("ctx := request.Context()")
		g.P("in, err := h.decoder.", endpoint.Name(), "(ctx, request)")
		g.P("if err != nil {")
		g.P("h.errorEncoder(ctx, err, writer)")
		g.P("return")
		g.P("}")
		g.P("out, err := h.service.", endpoint.Name(), "(ctx, in)")
		g.P("if err != nil {")
		g.P("h.errorEncoder(ctx, err, writer)")
		g.P("return")
		g.P("}")
		g.P("if err := h.encoder.", endpoint.Name(), "(ctx, writer, out); err != nil {")
		g.P("h.errorEncoder(ctx, err, writer)")
		g.P("return")
		g.P("}")
		g.P("})")
		g.P("}")
		g.P()
	}
	return nil
}
